## Python for DS Week-2 Practise File

In [4]:
# import necessary libraries

In [2]:
import pandas as pd

### Concatenate

Dataset: Two separate DataFrames df1 (employees from 2022) and df2 (employees from 2023)

In [3]:
df1 = pd.read_excel('Pandas_Practice_Data.xlsx',sheet_name='Concatenate_df1')
df1.head(1)

  Employee_ID   Name  Salary Designation  Year
0       E1000  Emp_0   65795   Associate  2022

In [4]:
df2 = pd.read_excel('Pandas_Practice_Data.xlsx',sheet_name='Concatenate_df2')
df2.head(1)

  Employee_ID    Name  Salary Designation  Year
0       E1050  Emp_50   80535     Manager  2023

#### 1.Create a final_df which consists of both the years data?

### Merging and Joining

Dataset: employee_info (personal details) and employee_performance (performance scores, salary)

In [34]:
emp_performance = pd.read_excel('Pandas_Practice_Data.xlsx',sheet_name='Merge_employee_performance')

emp_info = pd.read_excel('Pandas_Practice_Data.xlsx',sheet_name='Merge_employee_info')

#### 2.Perform an inner merge on Employee_ID to get a DataFrame with all employees who have performance records. How many employees are missing performance scores?

#### 3.Merge employee_info and employee_performance using a left join. Identify employees who do not have any performance score recorded.

#### 4.Perform an outer join on Employee_ID to create a combined DataFrame. Which columns have NaN values and why?

### Reshaping

Dataset: monthly_sales with columns Employee_ID, Jan_Sales, Feb_Sales, Mar_Sales

In [38]:
mont_sales = pd.read_excel('Pandas_Practice_Data.xlsx',sheet_name='Reshape_monthly_sales')
mont_sales.head(1)

  Employee_ID  Jan_Sales  Feb_Sales  Mar_Sales
0       E1000       7617       8164       7541

#### 5. Melt the DataFrame to convert monthly sales into a long format with columns: Employee_ID, Month, Sales. Which employee has the highest monthly sale in this format?

### Duplicate

Dataset: employee_data may contain duplicate entries

In [45]:
emp_data = pd.read_excel('Pandas_Practice_Data.xlsx',sheet_name='Duplicate_employee_data')
emp_data.head(1)

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Joining_Date,Experience_Years,City,Performance_Score
0,E1000,Emp_0,41,M,Sales,Associate,119836,2015-01-01,16,Mumbai,72

#### 6.Identify all duplicate rows in the employee_data. How many duplicates exist?

#### 7.Find the duplicates while keeping the last occurrence. What is the difference compared to keeping the first occurrence?

### Dropping Rows and Columns

Dataset: Drop_data

In [57]:
df = pd.read_excel('Pandas_Practice_Data.xlsx',sheet_name='Drop_data')
df.head(1)

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Joining_Date,Experience_Years,City,Performance_Score,Phone_Number,Address
0,E1000,Emp_0,41,M,Sales,Associate,119836.0,2015-01-01,16,Mumbai,72,9999957400,Address_0

#### 8.Drop the Phone_Number and Address columns permanently from the DataFrame. How does this affect the dataset shape?

#### 9.Drop all employees who belong to the 'Associate' designation.

### Rename & Replace

Dataset: employee_data

In [71]:
df = pd.read_excel('Pandas_Practice_Data.xlsx',sheet_name='Rename_data')
df.head(1)

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Joining_Date,Experience_Years,City,Performance_Score
0,E1000,Emp_0,41,M,Sales,Associate,119836,2015-01-01,16,Mumbai,72

#### 10. Reaname the Employee_ID to emp_id?

#### 11.Replace Gender values 'M' and 'F' with 'Male' and 'Female'. How does this improve readability?

#### 12.Find the number of type of departments and each department type count

### Pivot Table

Dataset: employee_data

df = pd.read_excel('Pandas_Practice_Data.xlsx',sheet_name='Pivot_data')

In [100]:

df.head(1)

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Joining_Date,Experience_Years,City,Performance_Score
0,E1000,Emp_0,41,M,Sales,Associate,119836,2015-01-01,16,Mumbai,72

#### 13.Create a pivot table showing average Salary for each Department and Designation. Which combination pays the most?

#### 14.Create a pivot table for avg Experience_Years per Department. Which department has the most experienced workforce?

#### 15.Create a pivot table showing average Performance_Score per City and Department. Which city-department combination performs best?

##### Cross Table

Dataset: employee_data

In [101]:

df.head(1)

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Joining_Date,Experience_Years,City,Performance_Score
0,E1000,Emp_0,41,M,Sales,Associate,119836,2015-01-01,16,Mumbai,72

#### 16.Create a cross tab between Department and Gender. How many males and females are in each department?

#### 17.Create a cross tab between Designation and City. Which city has the highest number of managers?

#### 18.Create a cross tab between Designation and Gender. What is the percentage of male employees in Associates?

#### 19.Add margins to the cross tab of Department vs Designation. What do the margins represent?

### Groupby in Pandas

Dataset: employee_data

In [102]:
df = pd.read_excel('Pandas_Practice_Data.xlsx',sheet_name='Groupby_data')
df.head(1)

,Employee_ID,Name,Age,Gender,Department,Designation,Salary,Joining_Date,Experience_Years,City,Performance_Score
0,E1000,Emp_0,41,M,Sales,Associate,119836,2015-01-01,16,Mumbai,72

#### 20.Group by Department and calculate average Salary. Which department is the highest paying?

#### 21.Group by Designation and count employees. Which designation is the most common?

#### 22.Group by Department and Gender, then calculate mean Performance_Score. Which group performs best?

### Summary Statistics

Dataset: employee_data

#### 23.Calculate summary statistics for Salary and Experience_Years. What insights can you draw about employee compensation?

#### 24.Find the median, max, and min Performance_Score for each department. Which department is performing consistently?

### Date-Time-Functions

Dataset: employee_data

#### 25.Convert Joining_Date to datetime format. How many employees joined after 2020-01-01?

#### 26.Extract the year and month from Joining_Date. Which month has the highest number of new joiners?

#### 27. Calculate the tenure of employees in years using Joining_Date and today’s date. Who has the longest tenure?

### Matplotlib

#### 28. Plot a scatter plot for the following data. Also add title and axis names

            bmi = (18, 34, 54, 45, 45, 45, 23, 23, 54)
            medical_claim = (145, 456, 764, 234, 156, 786, 345, 455, 675)

#### 29. Plot a pie chart for the following data

        prices = [50, 25, 50, 20]
        labels = ['Apple', 'Orange','Banana', 'Mango']

#### 30. Use 'Returns.csv'. Plot a multiple line plot showing each company returns using line plot.

#### 31. Create a 2×2 subplot grid containing the following visualizations: (Use iris data from seaborn librabry)

1.A histogram of sepal_length

2.A Box Plot of petal_length

3.A scatter plot of sepal_width vs. petal_width

4.A count plot showing the number of samples per species

### Seaborn

### 32.Using the 'diamonds' data available in the library seaborn, solve the following questions:
                    
1.Using multiple boxplot find the relation between `price` and type of `cut`  

2.Using Violin Plot find the distribution of price of diamods based on type of cut.

3.Using boxplot visualize the outliers in price of diamonds.

4.Using violin plot find the distribution of depth of diamond based on cut and color. 

5.Using count plot find the relation between cut and color of diamond.

### 33.Using the 'titanic' data available in the library seaborn, solve the following questions:

1. using swarm plot find the distribution of fare based on class. 

2. Using strip plot find the distribution of age based on Gender.

3. Using scatter plot find the relation between age and fare.

4. Using scatter plot find the relation between age and fare use class as hue.

5. Using histplot Find the distribution of Age variable.

### 34.Using below data solve the following questions.

data = {
'Experience': [1, 2, 3, 1, 4, 5, 6, 2, 3, 7, 8, 9, 5, 6, 7, 10, 12, 8, 6, 4],
'Salary': [30000, 35000, 40000, 32000, 45000, 50000, 55000, 37000, 42000, 60000,65000, 70000, 52000, 58000, 62000, 75000, 80000, 68000, 60000, 45000],
'Designation': ['Associate','Associate','Associate','Associate','Associate','Associate','Manager','Associate','Associate','Manager',
'Manager','Manager','Manager','Manager','Manager','Manager','Manager','Manager','Manager','Associate']
}

df = pd.DataFrame(data)

1. Using regplot find the relation between Experience & Salary. 

2. Using relplot find the relation between Experience & Salary based on designation.

3. Using lmplot find the relation between Experience & Salary based on designation.

### 35. Using pair plot identify relationship among all the numerical variables relation of iris data.