# Python for Data Science Week-1 Notebook

## Table of Content

1. **[What is Python Numpy](#python_numpy)**
2. **[Functions to Create Array](#functions)**
3. **[Attributes and Functions on Array](#operations)**
4. **[Indexing Array](#Indexing)**
5. **[Slicing Array](#Slicing)**
6. **[Operations on a 1D Array](#operations_1d)**
7. **[Operations on a 2D Array](#operations_2d)**
8. **[Arithmetic Functions in Numpy](#arithmetic_functions)**
9. **[Concatenation of Array](#concatenation)**
10. **[Pandas](#pandas)**

11. **[Data Structures](#structures)**
    
12. **[Pandas Series](#series)**
    - 12.1 - [Creating a Series](#creatingS)

13. **[Pandas DataFrames](#dataframes)**
    - 13.1 - [Creating DataFrames](#creatingDF)
    - 13.2 - [Manipulating DataFrames](#manipulatingDF)

14. **[Reading Data from Different Sources](#reading_data)**

<a id="python_numpy"> </a>
### 1. What is Python Numpy

The NumPy is a python package that stands for ‘Numerical Python’.<br>
                    Numpy is the core library for scientific computing, which contains a powerful n-dimensional array object, provides tools for integrating C, C++, etc.<br>
                    It contains a powerful N-dimensional array object.<br>

**How to install numpy?**<br>
1. You can use-<br>
`!pip install numpy`<br>
2. You can import it as-<br>
import numpy as np

In [65]:
# Import numpy librabry

In [66]:
import numpy as np

In [67]:
import pandas as pd

In [68]:
import matplotlib.pyplot as plt

In [69]:
import seaborn as sns

#### Python NumPy Array v/s List
We use python numpy array instead of a list because of the below three reasons:
1. Arrays occupy less memory<br>
2. work faster<br>
3. are convenient to use

#### Advantages of numpy arrays over lists

In [70]:
# create a Numpy array using arange of size 1000000
my_array = np.arange(1000000)

# create a python list using range of size 1000000
my_list = list(range(1000000))

In [71]:
print(type(my_array))
print(type(my_list))
my_array
my_array ** 2

<class 'numpy.ndarray'>
<class 'list'>

array([           0,            1,            4, ..., 999994000009,
       999996000004, 999998000001])

In [72]:
# print out execution time for the following

# time required for computations in an array
%time for _ in range(10): my_modified_array = my_array ** 2

# time required for computation in an array
%time for _ in range(10): my_modified_list = [x ** 2 for x in my_list]

CPU times: user 13.5 ms, sys: 2.07 ms, total: 15.5 ms
Wall time: 15.2 ms
CPU times: user 680 ms, sys: 137 ms, total: 817 ms
Wall time: 817 ms

From the above result, you can observe that the numpy arrays are faster than python lists.

Here Wall time, also called wall-clock time, measures the total time to execute a program in a computer.

<a id="functions"> </a>
### 2. Functions to Create Array

##### Create an array using np.array() function

In [73]:
arr = np.array(range(2, 6))
print(arr)
type(arr)

[2 3 4 5]

numpy.ndarray

In [74]:
import numpy as np

# 1. Create a 2D array from a list of lists
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("From list of lists:\n", array_2d)

# 2. Create a 2D array of zeros with a specific shape (rows, columns)
zeros_2d = np.zeros((3, 4))
print("\n3x4 array of zeros:\n", zeros_2d)

# 3. Create a 2D array with random values
random_2d = np.random.rand(2, 2)
print("\n2x2 array of random values:\n", random_2d)

From list of lists:
 [[1 2 3]
 [4 5 6]]

3x4 array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

2x2 array of random values:
 [[0.95501584 0.22799688]
 [0.24885886 0.13888568]]

##### create an array from list using array() function.

In [75]:
height = [5.2,  5.4, 4.4, 4.5, 5.6, 6]
weight = [81, 55, 65, 70, 45, 44]

In [76]:
height_arr = np.array(height)
weight_arr = np.array(weight)
height_arr
weight_arr

array([81, 55, 65, 70, 45, 44])

#####  Create an array using `arange()`

arange() function creates an array of numbers between the given range

In [77]:
np.arange(10,23)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

<a id="operations"> </a>
### 3. Attributes and Functions on Array

#### 3.1. Attributes:

It is defined as a specification that defines a property of an object. Attributes of the numpy array do not have parentheses following them

##### ndim:
Prints the dimension (number of axes) of the numpy array

In [78]:
height_arr.ndim

1

In [79]:
arr_2d  = np.array([[1,2,3], [4, 5, 6]])
arr_2d.ndim

2

##### dtype:
Prints the data type along with the size in bytes.

In [80]:
height_arr.dtype

dtype('float64')

##### shape
Prints the number of rows and columns of the array.

In [81]:
height_arr.shape

(6,)

In [82]:
arr_2d = np.array([[1,2,3], [4, 5, 6], [7,8 , 9]])
print(arr_2d)
print(arr_2d.ndim)
print(arr_2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)

In [83]:
import numpy as np

# Your array (2D: rows and columns)
print(f"Your array ndim: {arr_2d.ndim}")
print(f"Your array shape: {arr_2d.shape}")

# A 3D array example (an array containing two 2x2 matrices)
arr_3d = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print(f"\n3D array ndim: {arr_3d.ndim}")
print(f"3D array shape: {arr_3d.shape}")
display(arr_3d)

Your array ndim: 2
Your array shape: (3, 3)

3D array ndim: 3
3D array shape: (2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#### 3.2. Functions/method:
A method is a function that belongs to an object. It takes parameters in the parentheses and returns the modified array.

##### reshape:
The reshape() is used to change the number of rows and columns of an array without changing the data.<br>

<table align="center">
    <td height = '100', width = '400'>
          <img src="https://github.com/markondavineeth25/nareshIT/blob/main/PDS/Week-1%20Files/Notebooks/reshape.png?raw=1">
        </td>
</table>

In [84]:
# create an array
quantity_1 = np.array([(8,9,10),(11,12,13)])
# print the array
# \n: print on a newline
print("The original array:\n", quantity_1)
print(quantity_1.ndim)
print(quantity_1.shape)

The original array:
 [[ 8  9 10]
 [11 12 13]]
2
(2, 3)

In [85]:
quantity_1.reshape(3,2)

array([[ 8,  9],
       [10, 11],
       [12, 13]])

<a id="Indexing"> </a>
### 4. Indexing Array

**Indexing in 1 dimension**

In [86]:
# declare an array
quantity = np.array([11, 22, 33, 24, 57, 473])

# print the array
print(quantity)

[ 11  22  33  24  57 473]

Each element in the array can be accessed by passing the positional index of the element.

In [87]:
print(quantity)
print(quantity[0])
print(quantity[-1])
print(quantity[::2])
print(quantity[2:])
print(quantity[:3:])

[ 11  22  33  24  57 473]
11
473
[11 33 57]
[ 33  24  57 473]
[11 22 33]

**Indexing in 2 dimensions**

In [88]:
# use this 2D array
quantity_2d = np.array([[101, 231, 321],
              [412, 512, 622],
              [712, 821, 912]])

# print the array
quantity_2d

array([[101, 231, 321],
       [412, 512, 622],
       [712, 821, 912]])

We can retrieve an element of the 2D array using two indices i and j - i selects the row, and j selects the column:

In [89]:
sample_2d_array = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("3x3 2D Array:")
print(sample_2d_array)

3x3 2D Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

In [90]:
print(sample_2d_array[0,0])
print(sample_2d_array[1,2])
print(sample_2d_array[2,2])

10
60
90

<a id="Slicing"> </a>
### 5. Slicing Array

**Slicing a 1D array**

In [91]:
# declare an array
price = [101, 121, 112, 123, 114]

The slice notation specifies a start and end value [start:end], where 'start' is inclusive but 'end' is exclusive.

In [92]:
price[1: 5 : 2]

[121, 123]

**Slicing a 2D array**

In [93]:
# use this 2D array
prices_2d = np.array([[101, 131, 122, 113, 143],
               [145, 165, 137, 318, 193],
               [240, 241, 252, 253, 324],
               [225, 126, 727, 928, 129]])

# print the array
prices_2d

array([[101, 131, 122, 113, 143],
       [145, 165, 137, 318, 193],
       [240, 241, 252, 253, 324],
       [225, 126, 727, 928, 129]])

In [94]:
prices_2d[0:2, 0:2]

array([[101, 131],
       [145, 165]])

In [95]:
prices_2d[1:,1:3]

array([[165, 137],
       [241, 252],
       [126, 727]])

In [96]:
prices_2d[2:,3:]

array([[253, 324],
       [928, 129]])

**Note:** The index returns an element of the array, the slice returns a list of elements.

<a id="operations_1d"> </a>
### 6. Operations on a 1D Array

In [97]:
# declare two arrays
# first array
first_arr = np.array([120,230,310,410,150])

# second array
second_arr = np.arange(5)

# third array
third_arr = np.arange(4)

##### Add the two arrays

In [98]:
print(first_arr)
print(second_arr)
print(first_arr + second_arr)

[120 230 310 410 150]
[0 1 2 3 4]
[120 231 312 413 154]

**Remark:** If you try to add arrays with different dimensions, you get an error.

<a id="operations_2d"> </a>
### 7. Operations on a 2D Array

Let’s create 2 two-dimensional arrays, array_a and array_b.

In [99]:
# declare two arrays
# first array
quantity_A = np.array([[33,12],[70,61]])

# print the array
print("The first array is \n",quantity_A)

# second array
quantity_B  = np.array([[43,51],[72,81]])

# print the array
print("The second array is \n",quantity_B)

The first array is
 [[33 12]
 [70 61]]
The second array is
 [[43 51]
 [72 81]]

In [100]:
# add the 2 arrays

In [101]:
quantity_A + quantity_B

array([[ 76,  63],
       [142, 142]])

In [102]:
# multiply the 2 arrays

In [103]:
quantity_A * quantity_B

array([[1419,  612],
       [5040, 4941]])

In [104]:
# add 2 to each element

In [105]:
quantity_A + 2

array([[35, 14],
       [72, 63]])

In [106]:
# subtract 2 from each element

In [107]:
quantity_A - 2

array([[31, 10],
       [68, 59]])

In [108]:
# multiply 2 to each element

**Matrix Multiplication**<br>

Use '@' operator to perform matrix multiplication (or matrix product).

In [109]:
quantity_A@quantity_B

array([[2283, 2655],
       [7402, 8511]])

<a id="arithmetic_functions"> </a>
### 8. Arithmetic Functions in Numpy

In [110]:
# given array
performance_scores = np.array([5,7,8,2,4])

**sum():**<br>
The sum() function adds all the values in the array and gives a scalar output.

In [111]:
np.sum(performance_scores)

np.int64(26)

**max():**<br>
The max function finds the highest value in the array.

In [112]:
np.max(performance_scores)

np.int64(8)

**min():**<br>
The min function finds the lowest value in the array.

In [113]:
np.min(performance_scores)

np.int64(2)

**mean():**<br>
The mean function finds the average value of the array.

In [114]:
np.mean(performance_scores)

np.float64(5.2)

**media():**<br>
The median function finds the median value of the array.

In [115]:
np.median(performance_scores)

np.float64(5.0)

**power():**<br>
The power function raises the numbers in the array to the given value.

In [116]:
np.power(performance_scores, 2)

array([25, 49, 64,  4, 16])

**var():**<br>
The var function finds the variance of the data.

In [117]:
np.var(performance_scores)

np.float64(4.5600000000000005)

**std():**<br>
The std function finds the standard deviation of the data.

In [118]:
np.std(performance_scores)

np.float64(2.1354156504062622)

<a id="concatenation"> </a>
### 9. Concatenation of Array

The arrays can be concatenated only if they have the same shape, except in the dimension corresponding to the axis of concatenation.

**Concatenate 1D array**

In [119]:
# concatenate two 1D arrays
# production on day 1
production_day_1 = np.array([11, 22, 13])

# production on day 2
production_day_2 = np.array([23, 22, 12])

In [120]:
prod_data_2_days = np.concatenate([production_day_1, production_day_2])
prod_data_2_days

array([11, 22, 13, 23, 22, 12])

You can also concatenate more than two arrays at once.

In [121]:
# production on day 3
production_day_3 = np.array([23,45])

In [122]:
np.concatenate([prod_data_2_days, production_day_3])

array([11, 22, 13, 23, 22, 12, 23, 45])

In [123]:
np.concatenate([production_day_1, production_day_2, production_day_3])

array([11, 22, 13, 23, 22, 12, 23, 45])

**Concatenate 2D array**

In [124]:
# create a 2D array
scores_player_1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(scores_player_1)
print(scores_player_1.shape)
print(scores_player_1.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2

In [125]:
# create a 2D array
scores_player_2 = np.array([[5, 6, 3],
                 [4, 9, 6]])
print(scores_player_2)
print(scores_player_2.shape)
print(scores_player_2.ndim)

[[5 6 3]
 [4 9 6]]
(2, 3)
2

**concatenate along the first axis**

In [126]:
np.concatenate((scores_player_1, scores_player_2), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 3],
       [4, 9, 6]])

**concatenate along the second axis**

In [127]:
np.concatenate((scores_player_1, scores_player_2), axis = 1)

array([[1, 2, 3, 5, 6, 3],
       [4, 5, 6, 4, 9, 6]])

**Concatenate 1D and 2D array**

**Note:** One can not concatenate the arrays with different dimensions

In [128]:
# np.concatenate((performance_scores, scores_player_1), axis = 0)

### 10. Pandas

Pandas contain data structures and data manipulation tools designed for data cleaning and analysis.
<br><br>
                        While pandas adopt much code from NumPy, the difference is that Pandas is designed for tabular, heterogeneous data. NumPy, by difference, is best suited for working with homogeneous numerical array data.<br><br>
                         The name Pandas is derived from the term 'panel data' (an econometrics term for multidimensional structured data sets).

**How to install pandas?**<br>
1. You can use-<br>
`!pip install pandas`<br>
2. You can import it as 'pd'<br>
import pandas as pd

 Import the pandas library; the following convention is used

So from now on, we will use `pd` instead of pandas.

### 11. Data Structures

Pandas has two data structures as follows:<br>
1. A Series is a 1-dimensional labelled array that can hold data of any type (such as integer, string, boolean, float, python objects). Its axis labels are collectively called an index.<br>
2. A DataFrame is a 2-dimensional labelled data structure with columns. It supports multiple data types.

### 12. Pandas Series

Pandas Series is a one-dimensional labelled array capable of holding any data type. However, a series is a sequence of similar data types, similar to an array, list, or column in a table. <br><Br>It will assign a labelled index to each item in the pd.Series. By default, each item will receive an index label from 0 to N, where N is the length of the Series minus one.

### 12.1 Creating a Series

##### 1. To create a numeric series

In [129]:
# create a numeric series
numbers = range(1,100,5)

In [130]:
# covert it to series
numbers_series = pd.Series(numbers)
numbers_series

0      1
1      6
2     11
3     16
4     21
5     26
6     31
7     36
8     41
9     46
10    51
11    56
12    61
13    66
14    71
15    76
16    81
17    86
18    91
19    96
dtype: int64

In [131]:
type(numbers_series)

pandas.core.series.Series

##### 2. To create an object series

In [132]:
# create an object series
string = ["Hi" , "How" ,"are", "you", "?"]

In [133]:
series_str = pd.Series(string)
series_str

0     Hi
1    How
2    are
3    you
4      ?
dtype: object

In [134]:
type(series_str)

pandas.core.series.Series

**3. To create a series by giving both numeric and string values**

In [135]:
# create a Series with an arbitrary list
pd.Series([1,2,'Hello', 'World', 14.3])

0        1
1        2
2    Hello
3    World
4     14.3
dtype: object

Here the numeric values are treated as object.

**4. To set index values for a series**

In [171]:
# declare a list of marks
marks = [60, 89, 74, 86]

# declare a list of subjects
subject = ["Maths", "Science", "English" , "Social Science"]

In [172]:
pd.Series(marks)

0    60
1    89
2    74
3    86
dtype: int64

In [173]:
marks_series = pd.Series(marks, index = subject)

In [174]:
marks_series

Maths             60
Science           89
English           74
Social Science    86
dtype: int64

**5. To print the values and index of the Series**

In [139]:
marks_series.values

array([60, 89, 74, 86])

In [140]:
marks_series.index

Index(['Maths', 'Science', 'English', 'Social Science'], dtype='object')

### 13. Pandas DataFrames

 A DataFrame is a tabular representation of data containing an ordered collection of columns, each of which can be a different type (such as numeric, string, boolean). <br><br>
                        The DataFrame has both row and column index; it can be thought of as a dict of Series all sharing the same index. In a data frame, the data is stored as one or more two-dimensional blocks rather than a list, dict, or some other collection of one-dimensional arrays. <br><br>
                        While a DataFrame is physically two-dimensional, it can be used to represent higher dimensional data in a tabular format using hierarchical indexing.

### 13.1 Creating DataFrames

#####  Creating a data frame from a dictionary

In [141]:
# create a dictionary
data = {'Subject': ['Maths', 'History', 'Science', 'English', 'Georaphy', 'Art'],
        'Marks': (45, 65, 78, 65, 80, 78),
        'GPA': [2.5, 3.0, 3.5, 2.0, 4.0, 4.0]}

In [142]:
type(data)

dict

In [143]:
data_frame = pd.DataFrame(data)
data_frame

    Subject  Marks  GPA
0     Maths     45  2.5
1   History     65  3.0
2   Science     78  3.5
3   English     65  2.0
4  Georaphy     80  4.0
5       Art     78  4.0

In [144]:
type(data_frame)

pandas.core.frame.DataFrame

In [145]:
type(data_frame['Subject'])

pandas.core.series.Series

#####  To create dataframe from lists

In [146]:
# declare the list 'Subject'
Subject = ['Maths', 'History', 'Science', 'English', 'Georaphy', 'Art']

# declare the list 'Marks'
Marks = [45, 65, 78, 65, 80, 78]

# declare the list 'CPA'
GPA = [2.5, 3.0, 3.5, 2.0, 4.0, 4.0]

In [151]:
pd.DataFrame({'Subject': Subject, 'Marks': Marks, 'GPA': GPA})

    Subject  Marks  GPA
0     Maths     45  2.5
1   History     65  3.0
2   Science     78  3.5
3   English     65  2.0
4  Georaphy     80  4.0
5       Art     78  4.0

In [160]:
pd.DataFrame([Subject, Marks, GPA], index=['Subject', 'Marks', 'GPA']).T

    Subject Marks  GPA
0     Maths    45  2.5
1   History    65  3.0
2   Science    78  3.5
3   English    65  2.0
4  Georaphy    80  4.0
5       Art    78  4.0

#####  To create dataframe from series

In [161]:
# declare the series 'Subject'
Subject = pd.Series(['Maths', 'History', 'Science', 'English', 'Georaphy', 'Art'])

# declare the series 'Marks'
Marks = pd.Series([45, 65, 78, 65, 80, 78])

# declare the series 'GPA'
GPA = pd.Series([2.5, 3.0, 3.5, 2.0, 4.0, 4.0])

In [166]:
pd.DataFrame([Subject, Marks, GPA], index=['Subject', 'Marks', 'GPA']).T

    Subject Marks  GPA
0     Maths    45  2.5
1   History    65  3.0
2   Science    78  3.5
3   English    65  2.0
4  Georaphy    80  4.0
5       Art    78  4.0

In [167]:
pd.DataFrame({'Subject': Subject, 'Marks': Marks, 'GPA': GPA})

    Subject  Marks  GPA
0     Maths     45  2.5
1   History     65  3.0
2   Science     78  3.5
3   English     65  2.0
4  Georaphy     80  4.0
5       Art     78  4.0

### Lets work on the Salaries dataframe from now

In [176]:
Salaries =pd.DataFrame(
    {
    'designation': [
        'Senior Manager', 'Manager', 'Associate', 'Manager', 'Associate', 'Senior Manager',
        'Associate', 'Manager', 'Senior Manager', 'Associate',
        'Manager', 'Manager', 'Senior Manager', 'Associate', 'Manager',
        'Senior Manager', 'Associate', 'Manager', 'Senior Manager', 'Associate',
        'Manager', 'Senior Manager', 'Associate', 'Manager', 'Associate',
        'Senior Manager', 'Manager', 'Associate', 'Senior Manager', 'Associate'
    ],
    'salary': [
        180000, 95000, 45000, 88000, 52000, 170000,
        48000, 100000, 160000, 46000,
        92000, 97000, 185000, 55000, 89000,
        175000, 49000, 93000, 168000, 50000,
        91000, 162000, 47000, 88000, 53000,
        190000, 94000, 56000, 172000, 51000
    ],
    'gender': [
        'Male', 'Female', 'Female', 'Male', 'Male', 'Female',
        'Other', 'Female', 'Male', 'Female',
        'Male', 'Female', 'Male', 'Other', 'Female',
        'Male', 'Male', 'Female', 'Female', 'Male',
        'Female', 'Male', 'Other', 'Male', 'Female',
        'Female', 'Male', 'Female', 'Male', 'Female'
    ],
    'experience': [
        18, 10, 3, 9, 2, 17,
        4, 11, 16, 3,
        10, 12, 19, 5, 9,
        18, 4, 11, 15, 3,
        10, 16, 5, 9, 2,
        20, 11, 4, 17, 3
    ],
    'age': [
        52, 38, 25, 36, 24, 55,
        27, 40, 50, 23,
        35, 42, 57, 28, 39,
        54, 26, 37, 48, 25,
        34, 49, 29, 33, 24,
        58, 41, 27, 53, 26
    ]
})
Salaries

# Terminology
# Columns ---> Variables, Features, Attributes
# Rows ---> Observations, Records, Datapoints

       designation  salary  gender  experience  age
0   Senior Manager  180000    Male          18   52
1          Manager   95000  Female          10   38
2        Associate   45000  Female           3   25
3          Manager   88000    Male           9   36
4        Associate   52000    Male           2   24
5   Senior Manager  170000  Female          17   55
6        Associate   48000   Other           4   27
7          Manager  100000  Female          11   40
8   Senior Manager  160000    Male          16   50
9        Associate   46000  Female           3   23
10         Manager   92000    Male          10   35
11         Manager   97000  Female          12   42
12  Senior Manager  185000    Male          19   57
13       Associate   55000   Other           5   28
14         Manager   89000  Female           9   39
15  Senior Manager  175000    Male          18   54
16       Associate   49000    Male           4   26
17         Manager   93000  Female          11   37
18  Senior Manager  168000  Female          15   48
19       Associate   50000    Male           3   25
20         Manager   91000  Female          10   34
21  Senior Manager  162000    Male          16   49
22       Associate   47000   Other           5   29
23         Manager   88000    Male           9   33
24       Associate   53000  Female           2   24
25  Senior Manager  190000  Female          20   58
26         Manager   94000    Male          11   41
27       Associate   56000  Female           4   27
28  Senior Manager  172000    Male          17   53
29       Associate   51000  Female           3   26

#####  To print head of the data

#####  To print tail of the data

#####  To obtain the dimension of the data

#####  To know some information of the data

#####  To check the data type of columns in the data frame

##### To check the data structure of column in data frame

### 13.2  Manipulating DataFrames

#####  Adding a new column to the data set

####  1.Indexing a dataframe using `.loc`

`DataFrame.loc[]` method is a method that takes only index labels and returns row or dataframe if the index label exists in the caller data frame. <br>
`DataFrame.loc[Row_names, column_names]` is used to select or index rows or columns based on their name.

##### Add a new row to the data set

A new row can be added using the `loc`

### Understanding loc by resetting Salaries dataframe index

####  2.Indexing a dataframe using `.iloc`

`DataFrame.iloc[]` method is used when the index label of a data frame is something other than numeric series of 0, 1, 2, 3….n or in case the user doesn’t know the index label.

In [149]:
# Here in the Salaries_reset data where the index in emp_id and if we try to index the data using default
# python indexing 0,1,2...n this will throw an error so we use iloc.
#Salaries_reset.loc[0] (uncomment and run this cell you will get error)

##### 3. Conditional subsetting

##### Selecting rows where the value of `age` is greater than 47

##### Subsetting the age more than 55 *or* salary column value more than 189000

##### Subsetting the age more than 55 *and* salary column value more than 189000

##### 4. Sort the data frame on the basis of values in a column

##### 5. Rank the dataframe

In [150]:
marks = pd.DataFrame({'Name':['Hari','Mike','Cena','Lyon','Veeru','Vian','Mani','Gopal','Misty','Loki'],'Scores':[45,65,65,76,76,87,89,91,98,99]})

##### 6. To check for missing values

We shall import a new dataset.

The function `.isnull` check whether the data is missing. The `sum()` sums the number of 'True' values in the column. The final output gives the number of missing values in each column.

### 14.  Reading Data from Different Sources

##### Read a CSV file

##### Read a `.xlsx` file

##### Read data from Seaborn library.