## Connection for MY Sql

#### 1. Install the MySQL server and Python connection driver

In [1]:
!apt-get update
!apt-get -y install mysql-server mysql-client
!pip install pymysql

Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,917 B in 2s (2,544 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mysql-client is already the newest version (8.0.46-0ubuntu0.22.04.3).
mysql-server is already the newest version (8.0.46-0ubuntu0.22.04.3).
0 upgraded, 0 newly installed, 0 to remove and 62 not upgraded.
Requirement already satisfied: pymysql in /usr/local/lib/python3.12/dist-packages (1.2.0)

In [2]:
!mkdir -p /nonexistent

In [3]:
# 2. Start the MySQL background service
!/etc/init.d/mysql start

 * Starting MySQL database server mysqld
   ...done.

In [4]:
# 1. Stop the current service
!sudo service mysql stop

# 2. Start MySQL in safe mode (bypassing grant tables)
import os
import time
os.system("sudo mysqld_safe --skip-grant-tables --skip-networking &")
time.sleep(5)  # Wait for it to start

# 3. Reset the root user password and authentication method
!mysql -e "FLUSH PRIVILEGES; ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'root'; FLUSH PRIVILEGES;"

# 4. Kill the safe mode process and restart normally
!sudo pkill mysqld
time.sleep(2)
!sudo /etc/init.d/mysql start

 * Stopping MySQL database server mysqld
   ...done.
 * Starting MySQL database server mysqld
   ...done.

In [5]:
import pymysql

# Try connecting with the new password 'root'
try:
    connection = pymysql.connect(
        host='localhost',
        user='root',
        password='root',
        charset='utf8mb4',
        cursorclass=pymysql.cursors.DictCursor
    )
    print("Successfully connected to MySQL!")

    with connection.cursor() as cursor:
        cursor.execute("SELECT VERSION();")
        result = cursor.fetchone()
        print(f"Database version: {result['VERSION()']}")

finally:
    if 'connection' in locals() and connection.open:
        connection.close()

Successfully connected to MySQL!
Database version: 8.0.46-0ubuntu0.22.04.3

In [6]:
%load_ext sql
%sql mysql+pymysql://root:root@localhost/

In [7]:
import pandas as pd
import pymysql

# Re-open connection for pandas
connection = pymysql.connect(
    host='localhost',
    user='root',
    password='root',
    charset='utf8mb4'
)

# Query using pandas directly to avoid the PrettyTable error
df = pd.read_sql("SHOW DATABASES;", connection)
#connection.close()
df

/tmp/ipykernel_18756/2058911319.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SHOW DATABASES;", connection)

             Database
0  information_schema
1               mysql
2  performance_schema
3                 sys

In [8]:
pd.read_sql("SHOW DATABASES;", connection)

/tmp/ipykernel_18756/1209528634.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("SHOW DATABASES;", connection)

             Database
0  information_schema
1               mysql
2  performance_schema
3                 sys

In [9]:
%config SqlMagic.style = 'DEFAULT'

In [10]:
# !pip install prettytable==2.5.0

In [11]:
%%sql
SHOW DATABASES;

 * mysql+pymysql://root:***@localhost/
4 rows affected.

[('information_schema',), ('mysql',), ('performance_schema',), ('sys',)]

In [12]:
%%sql
SELECT DATABASE();

 * mysql+pymysql://root:***@localhost/
1 rows affected.

[(None,)]

In [15]:
%%sql
CREATE DATABASE NARESH_IT_DATABASE;

 * mysql+pymysql://root:***@localhost/
1 rows affected.

[]

In [17]:
%%sql
USE NARESH_IT_DATABASE;

 * mysql+pymysql://root:***@localhost/
0 rows affected.

[]

In [19]:
%%sql
CREATE TABLE DEPARTMENTS(
DEPT_ID INT PRIMARY KEY,
DEPT_NAME VARCHAR(30) NOT NULL);

 * mysql+pymysql://root:***@localhost/
0 rows affected.

[]

In [20]:
%%sql
CREATE TABLE EMPLOYEES (
EMP_ID INT PRIMARY KEY,
EMP_NAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) UNIQUE,
AGE INT CHECK (AGE > 18),
LOCATION VARCHAR(20) DEFAULT 'HYDERABAD',
SALARY DECIMAL(10,2),
DEPT_ID INT,
FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENTS(DEPT_ID));

 * mysql+pymysql://root:***@localhost/
0 rows affected.

[]

In [27]:
%%sql
SELECT * FROM EMPLOYEES;

 * mysql+pymysql://root:***@localhost/
0 rows affected.

[]

In [25]:
%%sql
select database();

 * mysql+pymysql://root:***@localhost/
1 rows affected.

[('NARESH_IT_DATABASE',)]

In [26]:
%%sql
ALTER TABLE EMPLOYEES
ADD COLUMN GENDER VARCHAR(10);

 * mysql+pymysql://root:***@localhost/
0 rows affected.

[]

In [30]:
%%sql
desc EMPLOYEES;

 * mysql+pymysql://root:***@localhost/
8 rows affected.

[('EMP_ID', 'int', 'NO', 'PRI', None, ''),
 ('EMP_NAME', 'varchar(50)', 'NO', '', None, ''),
 ('EMAIL', 'varchar(50)', 'YES', 'UNI', None, ''),
 ('AGE', 'int', 'YES', '', None, ''),
 ('LOCATION', 'varchar(20)', 'YES', '', 'HYDERABAD', ''),
 ('SALARY', 'decimal(10,2)', 'YES', '', None, ''),
 ('DEPT_ID', 'int', 'YES', 'MUL', None, ''),
 ('GENDER', 'varchar(10)', 'YES', '', None, '')]

In [31]:
%%sql
INSERT INTO DEPARTMENTS(DEPT_ID,DEPT_NAME)
VALUES (100,'ADMIN'),(101,'IT');

 * mysql+pymysql://root:***@localhost/
2 rows affected.

[]

In [33]:
%%sql
select * from DEPARTMENTS;

 * mysql+pymysql://root:***@localhost/
2 rows affected.

[(100, 'ADMIN'), (101, 'IT')]

In [34]:
%%sql
INSERT INTO EMPLOYEES
VALUES
(1,'RAKESH','RAKESH@GMAIL.COM',30,'HYDERABAD',50000,100,'MALE'),
(2,'POOJITHA','POOJITHA@GMAIL.COM',26,'HYDERABAD',75000,101,'FEMALE'),
(3,'ADHIRAN','ADHIRAN@GMAIL.COM',19,'HYDERABAD',100000,100,'MALE');

 * mysql+pymysql://root:***@localhost/
3 rows affected.

[]

In [36]:
%%sql
select * from EMPLOYEES;

 * mysql+pymysql://root:***@localhost/
3 rows affected.

[(1, 'RAKESH', 'RAKESH@GMAIL.COM', 30, 'HYDERABAD', Decimal('50000.00'), 100, 'MALE'),
 (2, 'POOJITHA', 'POOJITHA@GMAIL.COM', 26, 'HYDERABAD', Decimal('75000.00'), 101, 'FEMALE'),
 (3, 'ADHIRAN', 'ADHIRAN@GMAIL.COM', 19, 'HYDERABAD', Decimal('100000.00'), 100, 'MALE')]

In [37]:
%%sql
UPDATE EMPLOYEES
SET LOCATION = 'BANGALORE'
WHERE EMP_ID =1;

 * mysql+pymysql://root:***@localhost/
1 rows affected.

[]

In [38]:
%%sql
select * from EMPLOYEES;

 * mysql+pymysql://root:***@localhost/
3 rows affected.

[(1, 'RAKESH', 'RAKESH@GMAIL.COM', 30, 'BANGALORE', Decimal('50000.00'), 100, 'MALE'),
 (2, 'POOJITHA', 'POOJITHA@GMAIL.COM', 26, 'HYDERABAD', Decimal('75000.00'), 101, 'FEMALE'),
 (3, 'ADHIRAN', 'ADHIRAN@GMAIL.COM', 19, 'HYDERABAD', Decimal('100000.00'), 100, 'MALE')]

###### DELETE---> IT WILL BE OPERATED ON A TABLE LEVEL.
WE CAN DELETE A COLUMN OR A ROW.

###### TRUNCATE ---> WHEN WE DO TRUNCATE IT WILL REMOVE ALL THE COLUMSN AND THE ROWS
BUT KEEPS THE STRUCTURE INTACT

###### DROP ----> IT WILL DELETE EVERYTHING THE DATA,STRUCTURE AND THE DATABASE.